name: Deploy to Cloudflare Pages
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: ".node-version"

      - name: Install dependencies
        uses: pnpm/action-setup@v2
        with:
          run_install: |
            - args: [--frozen-lockfile, --strict-peer-dependencies]

      - run: pnpm run "/check\:/"
      - run: pnpm run build

      - name: Publish
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy build --project-name=lrc-maker
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
